In [1]:
import tensorflow as tf
import numpy as np

In [2]:
n_inputs = 3
n_neurons = 5
X1 = tf.placeholder(tf.float32,[None,n_inputs])
X2 = tf.placeholder(tf.float32,[None,n_inputs])
W_x = tf.get_variable("W_x",shape=[n_inputs,n_neurons],dtype=tf.float32,initializer=None,regularizer=None,trainable=True,collections=None)
W_y = tf.get_variable("W_y",shape=[n_neurons,n_neurons],dtype=tf.float32,initializer=None,regularizer=None,trainable=True,collections=None)
b = tf.get_variable("b",shape=[1,n_neurons],dtype=tf.float32,initializer=None,regularizer=None,trainable=True,collections=None)
Y1 = tf.nn.relu(tf.matmul(X1,W_x)+b)
Y2 = tf.nn.relu(tf.matmul(Y1,W_y)+tf.matmul(X2,W_x)+b)
init_op = tf.global_variables_initializer()

In [3]:
init_op = tf.global_variables_initializer()


In [4]:
X1_batch = np.array([[0,2,3],[2,8,9],[5,3,8],[3,4,5]])
X2_batch = np.array([[5,6,7],[8,3,4],[5,6,1],[3,6,1]])

In [5]:
with tf.Session() as sess:
    init_op.run()
    Y1_val,Y2_val = sess.run([Y1,Y2],feed_dict = {X1: X1_batch,X2: X2_batch})
    



In [6]:
print(Y1_val)
print(Y2_val)

[[  0.           0.           2.60617614   0.           0.89150929]
 [  0.           0.          10.00212479   0.           0.7726047 ]
 [  0.           0.           7.34832478   0.           3.60931635]
 [  0.           0.           6.49924755   0.           0.73300123]]
[[ 0.          0.          8.9674654   0.          0.        ]
 [ 0.          0.          5.86621952  0.          0.        ]
 [ 0.          0.          6.31855488  0.          0.        ]
 [ 0.          0.          5.80497646  0.          0.        ]]


In [4]:
basic_cell = tf.nn.rnn_cell.BasicRNNCell(num_units=n_neurons)
output_seqs, states = tf.contrib.rnn.static_rnn(basic_cell,[X1,X2],dtype=tf.float32)
Y1,Y2 = output_seqs
init_op = tf.global_variables_initializer()
X1_batch = np.array([[1,2,3],[2,3,4],[3,4,5],[4,5,6]])
X2_batch = np.array([[4,5,6],[5,6,7],[6,7,8],[7,8,9]])
with tf.Session() as sess:
    init_op.run()
    Y1_val,Y2_val = sess.run([Y1,Y2],feed_dict = {X1: X1_batch,X2: X2_batch})
print(Y1_val)
print(Y2_val)

[[-0.30452564  0.47166437  0.59854937  0.88386142 -0.81324553]
 [-0.67559958  0.71029574  0.73806047  0.97278959 -0.9186703 ]
 [-0.86862409  0.85198563  0.83412004  0.99384719 -0.96570724]
 [-0.95020825  0.92732197  0.89703906  0.99862015 -0.98574257]]
[[-0.7520746   0.95847178  0.98553461  0.98315871 -0.98124242]
 [-0.88307416  0.98106056  0.99552763  0.99052644 -0.99148756]
 [-0.95130157  0.99114561  0.99812704  0.99648619 -0.99618334]
 [-0.98082829  0.99581939  0.99906635  0.99898905 -0.99832106]]
